### ISSUE TITLE
New Version Issue: Cannot read properties of undefined (reading 'Partitions')

### ISSUE THREAD

**Issue by MaverickC2** [matthillman/homebridge-tc-2-0#5]
When Homebridge starts, it always shows the alarm as armed for HOME. Throws this error:

[TotalConnect] [getStatus] TypeError: Cannot read properties of undefined (reading 'Partitions')

**Comment by MaverickC2** [comment]
This error comes up as well and then homebridge restarts:

TypeError: Cannot read properties of undefined (reading 'Partitions')
    at TCApi.getStatus (/usr/local/lib/node_modules/homebridge-tc-security-panel/src/tc.v2.ts:263:63)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tc-security-panel/src/tcAccessory.ts:56:22

**Comment by egyptiangio** [comment]
Same issue here.

**Comment by njmike73** [comment]
I have this issue as well!

**Comment by upcsymbol** [comment]
[12/28/2022, 1:38:09 PM] [TotalConnect] [getStatus] TypeError: Cannot read properties of undefined (reading 'Partitions')

tc.v2.js
//response = await this.apiGET(${await this.getLocation()}/partitions/status);
response = await this.apiGET(${await this.getLocation()}/partitions/fullStatus);
