### ISSUE TITLE
TypeError: Cannot read property 'Partitions' of undefined

### ISSUE THREAD

**Issue by njmike73** [matthillman/homebridge-tc-2-0#7]
I am getting the error stated in the title but more info is below: (I did mask the directory it's running in for security)

(node:9468) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Partitions' of undefined
    at TCApi.getStatus (******\npm\node_modules\homebridge-tc-security-panel\src\tc.v2.ts:263:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Timeout._onTimeout (******\npm\node_modules\homebridge-tc-security-panel\src\tcAccessory.ts:56:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by flipit** [comment]
I've created a pull request which should solve the issue. I've not tested it though. I can't where I am. If anyone wants to test and confirm. The code is in the pull request.

**Comment by vlamb** [comment]
My error is similar and causes HomeBridge to restart. (I also made comment in the Pull)
TypeError: Cannot read properties of undefined (reading 'Partitions')
    at TCApi.getStatus (/usr/local/lib/node_modules/homebridge-tc-security-panel/src/tc.v2.ts:263:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tc-security-panel/src/tcAccessory.ts:56:22)

**Comment by upcsymbol** [comment]
[12/28/2022, 1:38:09 PM] [TotalConnect] [getStatus] TypeError: Cannot read properties of undefined (reading 'Partitions')

tc.v2.js
//response = await this.apiGET(`${await this.getLocation()}/partitions/status`);
response = await this.apiGET(`${await this.getLocation()}/partitions/fullStatus`);
